name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir
      run: mkdir obj
    - name: mkdir2
      run: mkdir build
    - name: make
      run: make
    - name: cd
      run: cd build
    - name: test
      run: ./test
